# Generated by Django 3.1.2 on 2020-11-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201116_1749'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(null=True, upload_to='upload/'),
        ),
        migrations.CreateModel(
            name='ManagerLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='location.location')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.manageruser')),
            ],
        ),
    ]
