# Generated by Django 3.1.2 on 2020-11-12 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.IntegerField(choices=[(1, 'Approve'), (2, 'Reject'), (3, 'Wait')], default=3),
        ),
        migrations.AddField(
            model_name='location',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(blank=True, max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
            ],
        ),
    ]
