# Generated by Django 3.1.2 on 2020-11-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(null=True, upload_to='upload/'),
        ),
    ]
