# Generated by Django 3.1.2 on 2020-11-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20201112_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='social_media',
            field=models.CharField(max_length=255),
        ),
    ]
