# Generated by Django 3.1.2 on 2020-11-14 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20201112_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='location_id',
            new_name='location',
        ),
    ]
