# Generated by Django 3.1.2 on 2020-11-17 21:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0005_auto_20201114_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('nfc_tag', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('status', models.IntegerField(choices=[(1, 'Approve'), (2, 'Reject'), (3, 'Wait')], default=3)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
            ],
        ),
    ]
