# Generated by Django 3.1.2 on 2020-12-15 14:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badges', '0002_auto_20201206_2359'),
        ('users', '0001_initial'),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='upload/collections/')),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending Approval')], default='PENDING', max_length=255)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(null=True)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.promoteruser')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rewards.reward')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionBadges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badges.badge')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badge_collections.collection')),
            ],
        ),
    ]
