# Generated by Django 3.1.2 on 2020-12-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
        ('badge_collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='reward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='rewards.reward'),
        ),
    ]
