# Generated by Django 3.1.2 on 2020-12-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge_collections', '0002_auto_20201215_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'permissions': (('check_collection_status', 'Can check completion status of a Collection'),)},
        ),
    ]
