# Generated by Django 3.1.2 on 2020-12-06 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('tags', '0001_initial'),
        ('locations', '0002_location_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='admin',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='users.adminuser'),
        ),
        migrations.AddField(
            model_name='tag',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
        migrations.AddField(
            model_name='redeemedcounters',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag'),
        ),
    ]
