# Generated by Django 3.1.2 on 2020-12-22 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20201206_2359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RedeemedCounters',
            new_name='RedeemedCounter',
        ),
    ]
