# Generated by Django 3.1.2 on 2020-12-13 00:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('locations', '0002_location_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending Approval')], default='PENDING', max_length=255)),
                ('time_redeem', models.IntegerField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.promoteruser')),
            ],
            options={
                'permissions': (('redeem_reward', 'Can redeem Reward'),),
            },
        ),
        migrations.CreateModel(
            name='RedeemableReward',
            fields=[
                ('reward_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('time_awarded', models.DateTimeField(auto_now_add=True)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appuser')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rewards.reward')),
            ],
        ),
    ]
