# Generated by Django 3.1.2 on 2021-01-02 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('rewards', '0002_auto_20201216_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemedReward',
            fields=[
                ('reward_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('time_awarded', models.DateTimeField(auto_now_add=True)),
                ('redeemed', models.BooleanField(default=False)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appuser')),
            ],
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'permissions': (('redeem_reward', 'Can redeem Reward'), ('view_stats', 'Can view statistics for a Reward'))},
        ),
        migrations.DeleteModel(
            name='RedeemableReward',
        ),
        migrations.AddField(
            model_name='redeemedreward',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rewards.reward'),
        ),
    ]
