# Generated by Django 3.1.2 on 2021-01-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_auto_20210102_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
