# Generated by Django 3.1.2 on 2020-12-06 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.manageruser'),
        ),
    ]
