# Generated by Django 3.1.2 on 2020-12-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='twitter',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
