# Generated by Django 3.1.2 on 2020-11-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20201130_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='facebook',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='instagram',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
