# Generated by Django 3.1.2 on 2020-11-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20201130_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.IntegerField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending Approval')], default='PENDING'),
        ),
    ]
