# Generated by Django 3.1.2 on 2020-12-22 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_twitter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'permissions': (('view_stats', 'Can view statistics for a location'),)},
        ),
    ]
