# Generated by Django 3.1.2 on 2020-12-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20201213_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='totalVisitors',
            new_name='total_visitors',
        ),
    ]
