# Generated by Django 3.1.2 on 2020-11-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20201130_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending Approval')], default='PENDING', max_length=255),
        ),
    ]
