# Generated by Django 3.1.2 on 2020-11-30 11:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_auto_20201130_1101'),
        ('users', '0003_auto_20201116_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='upload/badges/')),
                ('status', models.IntegerField(choices=[(1, 'Approve'), (2, 'Reject'), (3, 'Wait')], default=3)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.promoteruser')),
            ],
        ),
    ]
