# Generated by Django 3.1.2 on 2020-12-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('badges', '0002_auto_20201206_2359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RedeemedBadges',
            new_name='RedeemedBadge',
        ),
    ]
