# Generated by Django 3.1.2 on 2020-12-13 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_auto_20201206_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemedbadges',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
