# Generated by Django 3.1.2 on 2020-11-30 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_auto_20201130_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 14, 20, 56, 790944)),
        ),
    ]
