# Generated by Django 3.1.2 on 2020-12-22 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_auto_20201216_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemedbadge',
            name='time_redeemed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
