# Generated by Django 3.1.2 on 2020-12-13 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_redeemedbadges_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redeemedbadges',
            old_name='date_joined',
            new_name='time_redeemed',
        ),
    ]
