# Generated by Django 3.1.2 on 2021-01-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_redeemedbadge_time_redeemed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'permissions': (('redeem_badge', 'Can redeem Badge'), ('view_stats', 'Can view statistics for a Badge'))},
        ),
    ]
