# Generated by Django 3.1.2 on 2020-11-30 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_auto_20201130_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 14, 21, 26, 567207)),
        ),
    ]
