# Generated by Django 3.1.2 on 2020-11-30 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0005_auto_20201130_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 14, 21, 31, 342229, tzinfo=utc)),
        ),
    ]
