# Generated by Django 3.1.2 on 2020-11-30 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0006_auto_20201130_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
